# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='featured_image',
            field=models.CharField(blank=True, help_text='The featured image is the image which will be displayed in the list of photosets.<br>To find it, click the image in the photoset and copy the url. For example, https://www.flickr.com/photos/146011281@N02/30965802203/in/album-72157676287467202/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='flickr_set_owner',
            field=models.ForeignKey(help_text='The flickr set owner is the Flickr album owner. To determine your ID, visit your Flickr profile page and look for it at the end of the URL. For example, "www.flickr.com/photos/<strong>12341234@N12</strong>/"', on_delete=django.db.models.deletion.CASCADE, to='pictures.Flickr_Account'),
        ),
    ]
